import { Inter } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import Image from "next/image";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  if (!session) {
    return redirect("/");
  }

  // console.log(session);
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen">
          <aside className="bg-blue-100 w-48 p-4">
            <div className="rounded-full overflow-hidden w-24 mx-auto aspec-square">
              <Image
                src={session.user.image}
                alt={"avatar"}
                width={256}
                height={256}
              />
            </div>
            <nav className="flex flex-col text-center mt-8 gap-4">
              <Link href={"/account"}>
                <span className="text-gray-700">My page</span>
              </Link>
              <Link href={"/analytics"}>Analytics</Link>
            </nav>
          </aside>
          {/* <Header /> */}
          <div className="max-w-4xl mx-auto px-6 mt-5"> {children}</div>
        </main>
      </body>
    </html>
  );
}
